### ISSUE TITLE
api 测试“未认证”

### ISSUE THREAD

**Issue by hutong236** [veops/cmdb-sdk-python#2]
# 测试代码
`"""
@date: 2023-08-21
@desc:
suppose a CI model book with field book_id, name and author,
this file show how to add, get, update and delete books.
"""

from cmdb import Option, get_client

URL = "http://192.168.1.10:8000/api/v0.1"
KEY ="6786172015b047df81ab7753f027783b"
SECRET = "gSm9W2~D4Vu#$wsQ1OidaZzEo?c!6Y@X"

def add_book():
    opt = Option(url=URL, key=KEY, secret=SECRET)
    cli = get_client(opt)
    book = {"id": 1, "book_id": 1, "book_name": "平凡的世界", "author": "路遥"}
    resp = cli.add_ci("book", book)
    print(resp.ci_id)  # suppose the return ci_id is 2, will be used in update and delete

def update_book():
    """update with ci_id"""
    opt = Option(url=URL, key=KEY, secret=SECRET)
    cli = get_client(opt)
    book = {"book_name": "《平凡的世界》"}
    cli.update_ci("book", ci_id=2, attrs=book)

def update_book2():
    """update with unique key in model"""
    opt = Option(url=URL, key=KEY, secret=SECRET)
    cli = get_client(opt)
    # suppose book_id is the unique key of book
    book = {"book_name": "《平凡的世界》"}
    cli.update_ci("book", attrs=book, book_id=1)

def get_book():
    opt = Option(url=URL, key=KEY, secret=SECRET)
    cli = get_client(opt)
    resp = cli.get_ci(q="_type:book")
    books = resp.result
    print(books)

def delete_book():
    opt = Option(url=URL, key=KEY, secret=SECRET)
    cli = get_client(opt)
    resp = cli.delete_ci(ci_id=2)
    print(resp.message)

a = get_book()`

# 报错内容
` ~/Downloads/cmdb/demo/cmdb-sdk-python/exmaples/ [main*] python3 ci.py
Traceback (most recent call last):
  File "/Users/hutong/Downloads/cmdb/demo/cmdb-sdk-python/exmaples/ci.py", line 56, in <module>
    a = get_book()
        ^^^^^^^^^^
  File "/Users/hutong/Downloads/cmdb/demo/cmdb-sdk-python/exmaples/ci.py", line 44, in get_book
    resp = cli.get_ci(q="_type:book")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cmdb/client.py", line 85, in get_ci
    return self.ci.get_ci(q, fl, facet, count, page, sort, ret_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cmdb/core/ci.py", line 134, in get_ci
    return self._get_ci(params)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cmdb/core/ci.py", line 58, in _get_ci
    self._check_err(resp)
  File "/opt/homebrew/lib/python3.11/site-packages/cmdb/core/ci.py", line 44, in _check_err
    raise CMDBError(msg)
cmdb.core.exc.CMDBError: 未认证`
是什么原因？

**Comment by PengchuanC** [comment]
You seem to have used incorrect key/secret credentials，the server returned a 401 error.
